apiVersion: v1
kind: Service
metadata:
  name: whoami
  annotations:
    # For demo purposes: Allow ip sharing (ingress controller must have the same annotation)
    metallb.universe.tf/allow-shared-ip: "gedoplan.demo"
spec:
  selector:
    app: whoami
  # type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
