*Installation of Ceph using Rook*

Starting point::
Ceph, as a distributed file system, and the appropriate storage provisioner can be installed using an operator called Rook (https://rook.io/). Rook can be cloned from GitHub: 
+
[code]
----
git clone https://github.com/rook/rook.git
----
+
From this project the following files have been used (copied) in this demo:
+
[%autowidth]
|===
|Demo directory|File|Origin

.3+|`1-operator`
|common.yaml
.3+|`deploy/examples`

|`crds.yaml`

|`operator.yaml`

|`2-cluster`
|`cluster.yaml`
|`deploy/examples`

|`3-storageclass`
|`storageclass.yaml`
|`deploy/examples/csi/rbd`

|`4-dashboard`
|`dashboard-external-http.yaml`
|`deploy/examples/external`

|===
+
The `kustomization.yaml` files are used for configuration.

Installation::
Run the following commands:
+
[code]
----
kubectl apply -k 1-operator
watch kubectl -n rook-ceph get pod (*)

kubectl apply -k 2-cluster
watch kubectl -n rook-ceph get pod (*)

kubectl apply -k 3-storageclass

kubectl apply -k 4-dashboard
----
+
The commands marked with (*) are used to check if the deployed pods are running properly.
The next command must not be executed until then.

Dashboard::
The Ceph Dashboard is published at `https://ceph.demo.gedoplan.demo` (internal TLS certificate):
* User: `admin`
* Password: generated by installer; see `kubectl -n rook-ceph get secret rook-ceph-dashboard-password -o jsonpath="{['data']['password']}" | base64 --decode && echo`