apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- storageclass.yaml

patches:
- patch: |-
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: rook-ceph-block
      annotations:
        "storageclass.kubernetes.io/is-default-class": "true"

