apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rook-ceph

resources:
- cluster.yaml

patches:
  - patch: |-
      apiVersion: ceph.rook.io/v1
      kind: CephCluster
      metadata:
        name: rook-ceph
        namespace: rook-ceph
      spec:
        mon:
          # The demo cluster is too small for the standard mon count of 3
          # Use only 1 mon for testing/demonstration purposes only!
          count: 1
        storage:
          useAllNodes: false
          useAllDevices: false
          config:
          nodes:
          - name: k8s-142
            devices:
            - name: sda2
          - name: k8s-143
            devices:
            - name: sda3
